Message {
    channelId: '823953904512411111',
    guildId: '8239539011111111',
    id: '129397484911111111',
    position: null,
    createdTimestamp: 1728578045109,
    type: 'DEFAULT',
    system: false,
    content: 'help me pls',
    author: User {
      id: '10957973234111111',
      bot: false,
      system: false,
      flags: UserFlags { bitfield: 0 },
      username: 'vas1111',
      globalName: null,
      discriminator: '0',
      avatar: null,
      banner: undefined,
      bannerColor: undefined,
      accentColor: undefined,
      avatarDecoration: null,
      avatarDecorationData: null,
      clan: null
    },
    pinned: false,
    tts: false,
    nonce: '12939748411111',
    embeds: [],
    components: [],
    attachments: Collection(0) [Map] {},
    stickers: Collection(0) [Map] {},
    editedTimestamp: null,
    reactions: ReactionManager { message: [Circular *1] },
    mentions: MessageMentions {
      everyone: false,
      users: Collection(0) [Map] {},
      roles: Collection(0) [Map] {},
      _members: null,
      _channels: null,
      _parsedUsers: null,
      crosspostedChannels: Collection(0) [Map] {},
      repliedUser: null
    },
    webhookId: null,
    poll: null,
    groupActivityApplication: null,
    applicationId: null,
    activity: null,
    flags: MessageFlags { bitfield: 0 },
    reference: null,
    interaction: null,
    call: null
  }