require("dotenv").config()

module.exports = {
    DISCORD_TOKEN: process.env.DISCORD_TOKEN,
    DISCORD_TREASURE_CHANNEL_WEBHOOK: process.env.DISCORD_TREASURE_CHANNEL_WEBHOOK,
    DISCORD_ARCADE_CHANNEL_WEBHOOK: process.env.DISCORD_ARCADE_CHANNEL_WEBHOOK,
    DISCORD_TEST_CHANNEL_WEBHOOK: process.env.DISCORD_TEST_CHANNEL_WEBHOOK,
}