const filters = [
    "government",
    "receive",
    "rewards",
    "reward",
    "drop",
    "event",
    "reward",
    "rewards",
    "free",
    "snapshot",
    "airdrop",
    "earn",
    "FCFS",
    "prize",
    "prizes",
    "DISTRIBUTION",
    "launch",
    "checker",
    "foundation",
    "multiplier",
    "claim",
    "bonus",
    "randomly selecting",
    "raffle",
    "snapshot",
    "season",
    "whitelist",
    "Quest",
    "mint",
    "Distribution",
    "receive",
    "ambassador",
    "role holder",
]